"""Added privacy to user

Revision ID: 225e181b11d5
Revises: 9b14239afae8
Create Date: 2025-01-03 18:56:45.004535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '225e181b11d5'
down_revision = '9b14239afae8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accepted_privacy_policy', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('accepted_privacy_policy')

    # ### end Alembic commands ###
