"""Added profile information to  User model

Revision ID: 46fe27e2a298
Revises: f437c2fb568a
Create Date: 2025-01-04 21:41:26.524482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46fe27e2a298'
down_revision = 'f437c2fb568a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('title', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('about_me', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('twitter', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('github', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('github')
        batch_op.drop_column('twitter')
        batch_op.drop_column('website')
        batch_op.drop_column('about_me')
        batch_op.drop_column('location')
        batch_op.drop_column('title')
        batch_op.drop_column('display_name')

    # ### end Alembic commands ###
