"""Add description column to subcategory

Revision ID: 67017f367a4b
Revises: b202a9b64c05
Create Date: 2025-01-08 21:45:12.883902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67017f367a4b'
down_revision = 'b202a9b64c05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subcategory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subcategory', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
