"""Add forum models (categories, subcategories, threads, comments)

Revision ID: f437c2fb568a
Revises: 225e181b11d5
Create Date: 2025-01-03 19:39:05.827068

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f437c2fb568a'
down_revision = '225e181b11d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subcategory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('post')
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('thread_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('comment_news_id_fkey', type_='foreignkey')
        batch_op.drop_column('news_id')

    with op.batch_alter_table('thread', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('subcategory_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('thread_category_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'subcategory', ['subcategory_id'], ['id'])
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thread', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('thread_category_id_fkey', 'category', ['category_id'], ['id'])
        batch_op.drop_column('subcategory_id')
        batch_op.drop_column('content')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('news_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('comment_news_id_fkey', 'news', ['news_id'], ['id'])
        batch_op.alter_column('thread_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))

    op.create_table('post',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('thread_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['thread.id'], name='post_thread_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='post_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='post_pkey')
    )
    op.drop_table('subcategory')
    # ### end Alembic commands ###
